######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 28 12:20:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += noise.h
SOURCES += main.cpp noise.cpp
